#!/usr/bin/env bash

MAKEFILEDIR=$(cd "$(dirname "$0")"; pwd)

case "$1" in
  clean) ACTION="clean";;
  *) ACTION="btags"
    SRCPATH="$1"
    if [[ "$SRCPATH" == "" ]]; then
      SRCPATH="$PWD"
    fi
    SRCPATH=$(realpath "$SRCPATH")
    ;;
esac

SRCDIR=$(realpath "$PWD")
TAGSDIR="$HOME/.btags$SRCDIR"
PATH="$PATH:$MAKEFILEDIR"

mkdir -p "$TAGSDIR"
cd "$TAGSDIR"

if [[ "$ACTION" == "clean" ]]; then
  make -j -r -s -f "$MAKEFILEDIR/Makefile" srcdir="$SRCDIR" clean
else
  make -j -r -s -f "$MAKEFILEDIR/Makefile" srcdir="$SRCDIR" check_commands
  make -j -r -s -f "$MAKEFILEDIR/Makefile" srcdir="$SRCDIR" 

  if [ -d "$SRCPATH" ]; then
    echo "$HOME/.btags$SRCPATH/tags.tags"
  else
    echo "$HOME/.btags$SRCPATH.tags"
  fi
fi
